@startuml

:User: as :U1:
rectangle "Github Pages" as U2
rectangle "A-Frame" as U3

package "Our Webpage" as UC1a {
(Load Webpage) as (1A)
(View Model) as (1B)
(View Video) as (1C)
}

(1B) -d[hidden]- (1C)
:U1: -r-> (1A)
(1A) <|- (1B)
(1A) <|- (1C)
U2 --> (1A) : <<Supporting>>
U3 -l-> (1B) : <<Supporting>>
U3 -l-> (1C) : <<Supporting>>

@enduml